#!/usr/bin/env ruby

require 'socket'

unless ARGV.length > 1
  puts "Supply the remote host and port as arguments"
  exit 1
end

host = ARGV[0]
port = ARGV[1].to_i

socket = TCPSocket.new(host, port)
# socket.connect host, port

for i in 1..100
  puts "Sending #{i}"
  socket.send "#{i}\n", 0
end

