var mobs = [
  {
    name: "Witch",
    type: "monster",
    health: 13,
    image: "http://www.minecraftopia.com/images/blocks/witch.png",
  },
  {
    name: "Chicken",
    type: "critter",
    health: 2,
    image: "http://www.minecraftopia.com/images/blocks/chicken.png",
  },
  {
    name: "Horse",
    type: "critter",
    health: 15,
    image: "http://www.minecraftopia.com/images/blocks/horse.png",
  },
  {
    name: "Cave Spider",
    type: "monster",
    health: 10,
    image: "http://www.minecraftopia.com/images/blocks/cave_spider.png",
  },
  {
    name: "Mooshroom",
    type: "critter",
    health: 5,
    image: "http://www.minecraftopia.com/images/blocks/mooshroom.png",
  },
  {
    name: "Cat",
    type: "critter",
    health: 10,
    image: "http://www.minecraftopia.com/images/blocks/cat.png",
  },
  {
    name: "Ocelot",
    type: "critter",
    health: 10,
    image: "http://www.minecraftopia.com/images/blocks/ocelot.png",
  },
  {
    name: "Spider",
    type: "monster",
    health: 10,
    image: "http://www.minecraftopia.com/images/blocks/spider.png",
  },
  {
    name: "Sheep",
    type: "critter",
    health: 5,
    image: "http://www.minecraftopia.com/images/blocks/sheep.png",
  },
  {
    name: "Snow Golem",
    type: "critter",
    health: 4,
    image: "http://www.minecraftopia.com/images/blocks/snow_golem.png",
  },
  {
    name: "Cow",
    type: "critter",
    health: 5,
    image: "http://www.minecraftopia.com/images/blocks/cow.png",
  },
  {
    name: "Squid",
    type: "critter",
    health: 5,
    image: "http://www.minecraftopia.com/images/blocks/squid.png",
  },
  {
    name: "Villager",
    type: "critter",
    health: 10,
    image: "http://www.minecraftopia.com/images/blocks/villager.png",
  },
  {
    name: "Bat",
    type: "critter",
    health: 3,
    image: "http://www.minecraftopia.com/images/blocks/bat.png",
  },
  {
    name: "Squid",
    type: "critter",
    health: 5,
    image: "http://www.minecraftopia.com/images/blocks/squid.png",
  },
  {
    name: "Blaze",
    type: "monster",
    health: 8,
    image: "http://www.minecraftopia.com/images/blocks/blaze.png",
  },
  {
    name: "Creeper",
    type: "monster",
    health: 10,
    image: "http://www.minecraftopia.com/images/blocks/creeper.png",
  },
  {
    name: "Enderman",
    type: "monster",
    health: 10,
    image: "http://www.minecraftopia.com/images/blocks/enderman.png",
  },
  {
    name: "Ghast",
    type: "monster",
    health: 5,
    image: "http://www.minecraftopia.com/images/blocks/ghast.png",
  },
];
